### ISSUE TITLE
Precompilation warnings

### ISSUE THREAD

**Issue by mlhetland** [JuliaIntervals/AffineArithmetic.jl#38]
When precompiling, I get some warnings:

```
julia> using AffineArithmetic
[ Info: Precompiling AffineArithmetic [2e89c364-fad6-56cb-99bd-ebadcd2cf8d2]
WARNING: method definition for literal_pow at /Users/mlh/.julia/packages/AffineArithmetic/JmzEi/src/aff.jl:98 declares type variable T but does not use it.
WARNING: method definition for zero at /Users/mlh/.julia/packages/AffineArithmetic/JmzEi/src/affine.jl:24 declares type variable N but does not use it.
WARNING: method definition for literal_pow at /Users/mlh/.julia/packages/AffineArithmetic/JmzEi/src/affine.jl:101 declares type variable T but does not use it.
```

For `literal_pow` (both cases), it seems maybe it's a `T` that has been replaced by the use of `typeof`?

For `zero`, it seems maybe it's a bug, as it uses `Affine{T}`, where the first type parameter of `Affine` is `N`. So I guess you should have `Affine{N, T}` in the left-hand side, even though you only use `T` on the right?

**Comment by schillic** [comment]
Hm, I think I only read the message above now. I agree that this indeed looks like a bug with the `zero`. In #39 I did not fix that bug. See the diff [here](https://github.com/JuliaIntervals/AffineArithmetic.jl/pull/39/files#diff-d0d748f14f22c99bec17d9279bbb5355463d87c678adc32d5153c612ddbf1129).
